felangel/flow_builder

example/lib/main.dart, example/lib/onboarding_flow.dart, example/lib/profile_flow.dart, lib/flow_builder.dart, pubspec.yaml
**READY**
YES
```dart
FlowBuilder<Profile>(
state: const Profile(),
builder: (context, profile, controller) {
return [
...
];
},
);
```
```dart
FlowBuilder<Profile>(
state: const Profile(),
builder: (context, profile) {
return [
...
];
},
);
```
The controller can be accessed immediately in the builder via `context.flow<T>()`.
=> feat!: remove controller from builder

.github/workflows/main.yaml, .gitignore, lib/flow_builder.dart, pubspec.yaml, test/flow_builder_test.dart
**READY**
NO
- test: 100% test coverage (closes #1)
=> test: 100% test coverage

CHANGELOG.md, README.md, example/lib/main.dart, example/lib/onboarding_flow.dart, example/lib/profile_flow.dart, lib/flow_builder.dart, pubspec.yaml, test/flow_builder_test.dart
**READY**
YES
- **BREAKING**: replace `builder` with `onGeneratePages`
- fix: navigation animation
- fix: system back navigation
```dart
class OnboardingFlow extends StatelessWidget {
@override
Widget build(BuildContext context) {
return FlowBuilder<OnboardingSteps>(
state: OnboardingSteps.step1,
builder: (context, state) {
switch (state) {
case OnboardingSteps.step1:
return [Step1.page()];
case OnboardingSteps.step2:
return [Step1.page(), Step2.page()];
case OnboardingSteps.step3:
return [Step1.page(), Step2.page(), Step3.page()];
default:
return [Step1.page()];
}
},
);
}
}
```
```dart
class OnboardingFlow extends StatelessWidget {
@override
Widget build(BuildContext context) {
return FlowBuilder<OnboardingSteps>(
state: OnboardingSteps.step1,
onGeneratePages: (state) {
switch (state) { …
```
=> feat!: add onGeneratePages

CHANGELOG.md, lib/flow_builder.dart, pubspec.yaml, test/flow_builder_test.dart
**READY**
NO
- feat: add onComplete (closes #5)
=> feat: add onComplete

CHANGELOG.md, example/lib/location_flow/location_flow.dart, example/lib/onboarding_flow.dart, example/lib/profile_flow.dart, lib/flow_builder.dart, pubspec.yaml, test/flow_builder_test.dart
**READY**
YES
- feat: include previous pages in `onGeneratePages`
=> feat: include pages in onGeneratePages

CHANGELOG.md, example/lib/location_flow/pages/city_selection/city_selection.dart, example/lib/location_flow/pages/country_selection/country_selection.dart, example/lib/location_flow/pages/state_selection/state_selection.dart, example/pubspec.yaml, lib/flow_builder.dart, pubspec.yaml, test/flow_builder_test.dart
**READY**
NO
- feat: `FlowBuilder` accepts an optional `FlowController<T>`
- feat: throw `FlutterError` when `context.flow` is called outside of a `FlowBuilder`
=> feat: v0.0.1-dev.8

CHANGELOG.md, lib/flow_builder.dart, pubspec.yaml, test/flow_builder_test.dart
**READY**
NO
- feat: add FakeFlowController
=> feat: add FakeFlowController

CHANGELOG.md, example/lib/location_flow/pages/country_selection/country_selection.dart, example/lib/onboarding_flow/onboarding_flow.dart, example/lib/profile_flow/profile_flow.dart, lib/flow_builder.dart, pubspec.yaml, test/flow_builder_test.dart
**READY**
YES
- feat!: FlowController Improvements
- **BREAKING** feat!: remove `Update` and `Complete` typedefs
- feat: update `FlowController` to have a public constructor
- feat: `FlowBuilder` requires either `state` or `controller`
- feat: `FlowController` exposes `addListener`, `removeListener`, and `dispose` (closes #10)
=> feat!: FlowController Improvements

CHANGELOG.md, example/lib/authentication_flow/authentication_flow.dart, example/lib/main.dart, lib/flow_builder.dart, test/flow_builder_test.dart
**READY**
NO
- feat: `FlowController` exposes `state`
- fix: support hardware back functionality on Android within nested flows
=> fix: SystemNavigation in nested flows on Android

lib/flow_builder.dart
READY
NO
This PR includes minor changes that makes the `FlowController` class listenable. This makes it easy to listen to state changes using the incredibly aptly named `AnimatedBuilder`.
=> feat: make flow controller listenable

CHANGELOG.md, lib/flow_builder.dart, pubspec.yaml, test/flow_builder_test.dart
**READY**
NO
- fix: FakeFlowController supports complete with no callback
=> fix: FakeFlowController supports complete with no callback

CHANGELOG.md, lib/flow_builder.dart, pubspec.yaml, test/flow_builder_test.dart
**READY**
NO
- fix: SystemNavigator pop behavior
=> fix: SystemNavigator pop behavior

.github/workflows/main.yaml, CHANGELOG.md, README.md, example/lib/authentication_flow/authentication_flow.dart, example/lib/location_flow/location_flow.dart, example/lib/location_flow/models/location.dart, example/lib/location_flow/models/location_state.dart, example/lib/location_flow/pages/city_selection/city_selection.dart, example/lib/location_flow/pages/country_selection/country_selection.dart, example/lib/location_flow/pages/state_selection/state_selection.dart, example/lib/location_flow/repository/data/cities.dart, example/lib/location_flow/repository/data/countries.dart, example/lib/location_flow/repository/data/states.dart, example/lib/location_flow/repository/location_repository.dart, example/lib/location_flow/widgets/drop_down_menu.dart, example/lib/main.dart, example/lib/onboarding_flow/onboarding_flow.dart, example/lib/profile_flow/profile_flow.dart, example/pubspec.yaml, lib/flow_builder.dart, pubspec.yaml, test/flow_builder_test.dart
**READY**
YES
Bumbed version of Dart, and migrated code to support null-safety.
=> feat(nndb)!: added support for null-safety

.github/workflows/main.yaml, example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata, example/lib/authentication_flow/authentication_flow.dart, example/lib/location_flow/location_flow.dart, example/lib/location_flow/models/location_state.dart, example/lib/location_flow/pages/city_selection/city_selection.dart, example/lib/location_flow/pages/city_selection/city_selection_cubit.dart, example/lib/location_flow/pages/country_selection/country_selection.dart, example/lib/location_flow/pages/country_selection/country_selection_cubit.dart, example/lib/location_flow/pages/state_selection/state_selection.dart, example/lib/location_flow/pages/state_selection/state_selection_cubit.dart, example/lib/location_flow/repository/location_repository.dart, example/lib/profile_flow/profile_flow.dart
**READY**
NO
- refactor: cleanup before v0.0.1
=> refactor: cleanup before v0.0.1

example/lib/onboarding_flow/onboarding_flow.dart, lib/flow_builder.dart, test/flow_builder_test.dart
**READY**
NO
- feat: add NavigatorObserver support (closes #19)
- docs: update example to include custom page transitions and hero animations
=> feat: add NavigatorObserver support

CHANGELOG.md, README.md, example/lib/onboarding_flow/onboarding_flow.dart, pubspec.yaml
=> chore: v0.0.1

example/lib/main.dart, example/pubspec.yaml, lib/flow_builder.dart, pubspec.yaml, test/flow_builder_test.dart
**READY**
NO
- If there is a `WillPopScope` at the root of a flow, `FlowBuilder` will invoke and respect the result of `willPop`.
- closes #44
=> fix: respect WillPopScope

.github/workflows/main.yaml
**READY**
NO
- ci: add pub score verification
=> ci: add pub score verification

CHANGELOG.md, pubspec.yaml
=> chore: v0.0.3

lib/flow_builder.dart
**READY**
NO
- `addListener` and `removeListener` were marked with `@mustCallSuper`
- fixes https://github.com/felangel/flow_builder/issues/54
=> fix: super call enforcement on listeners

example/lib/location_flow/pages/city_selection/city_selection.dart, example/lib/location_flow/pages/country_selection/country_selection.dart, example/lib/location_flow/pages/state_selection/state_selection.dart, example/lib/main.dart, example/lib/onboarding_flow/onboarding_flow.dart, example/lib/profile_flow/profile_flow.dart, lib/flow_builder.dart, test/flow_builder_test.dart
**READY**
NO
- refactor: organize imports and minor updates
=> refactor: organize imports and minor updates

lib/flow_builder.dart
**READY**
NO
- refactor: decouple FlowController from FlowBuilder
=> refactor: decouple FlowController from FlowBuilder

CHANGELOG.md, example/linux/flutter/generated_plugin_registrant.cc, example/linux/flutter/generated_plugin_registrant.h, pubspec.yaml
=> chore: v0.0.4

.github/workflows/main.yaml
**READY**
NO
- ci: upgrade to flutter-action v1.5.3
=> ci: upgrade to flutter-action v1.5.3

CHANGELOG.md, pubspec.yaml
**READY**
NO
Bump version 0.0.5 to update the package in pub.dev
=> chore: v0.0.5

example/ios/Flutter/AppFrameworkInfo.plist, lib/flow_builder.dart, test/flow_builder_test.dart
**READY**
YES
- refactor: FlowController notification behavior updates
- refactor!: `protected` setter for `FlowController` `state` has been removed in favor of using `controller.update`.
=> refactor: FlowController notification behavior updates

lib/flow_builder.dart, test/flow_builder_test.dart
**READY**
NO
- fix: removeListener when FlowController is complete
- closes #73
=> fix: removeListener when FlowController is complete

CHANGELOG.md, pubspec.yaml
=> chore: v0.0.6

.github/workflows/main.yaml, example/lib/main.dart
**READY**
NO
- ci: upgrade to flutter-action@v2
=> ci: upgrade to flutter-action@v2

example/linux/flutter/generated_plugins.cmake, example/windows/flutter/generated_plugins.cmake, lib/flow_builder.dart
**READY**
NO
- refactor: remove null-aware operand
=> refactor: remove null-aware operand

CHANGELOG.md, pubspec.yaml
=> chore: v0.0.7

example/analysis_options.yaml, example/ios/Runner/Info.plist, example/lib/authentication_flow/authentication_flow.dart, example/lib/location_flow/pages/city_selection/city_selection.dart, example/lib/location_flow/pages/state_selection/state_selection.dart, example/lib/location_flow/widgets/drop_down_menu.dart, example/lib/main.dart, example/lib/onboarding_flow/onboarding_flow.dart, example/pubspec.yaml
**READY**
NO
- refactor: upgrade example to Flutter 3.0.0
=> refactor: upgrade example to Flutter 3.0.0

CHANGELOG.md, pubspec.yaml
**READY**
YES
- fix: add dart sdk >=2.17.0 constraint (should have been applied in v0.0.7)
=> fix: add dart sdk >=2.17.0 constraint

test/flow_builder_test.dart
**READY**
NO
Changes:
- Grouped constructor related test inside a group. In order to improve readability and maintainability of the code.
- Included missing test case scenario where state is not null and controller is null
=> test: grouped constructor tests and added missing test

.github/workflows/main.yaml, example/lib/authentication_flow/authentication_flow.dart, example/lib/location_flow/pages/city_selection/city_selection.dart, example/lib/location_flow/pages/country_selection/country_selection.dart, example/lib/location_flow/pages/state_selection/state_selection.dart, example/lib/location_flow/widgets/drop_down.dart, example/lib/location_flow/widgets/widgets.dart, example/lib/onboarding_flow/onboarding_flow.dart, example/lib/profile_flow/profile_flow.dart, test/flow_builder_test.dart
**READY**
NO
- ci: use latest stable flutter
=> ci: use latest stable flutter

lib/flow_builder.dart
**READY**
NO
Add optional `clipBehavior` property for more control over the shown page.
=> feat: add optional `clipBehavior`

.github/workflows/main.yaml
**READY**
NO
- ci: use pana workflow
=> ci: use pana workflow

analysis_options.yaml, example/analysis_options.yaml, example/lib/authentication_flow/authentication_flow.dart, example/lib/location_flow/pages/city_selection/city_selection.dart, example/lib/location_flow/pages/state_selection/state_selection.dart, example/lib/location_flow/widgets/drop_down.dart, example/lib/main.dart, example/pubspec.yaml, lib/flow_builder.dart, pubspec.yaml
**READY**
NO
- refactor: update lint rules
=> refactor: update lint rules

pubspec.yaml
**READY**
NO
- chore: add `funding` to `pubspec.yaml`
=> chore: add `funding` to `pubspec.yaml`
